version: '3.3'
services:
  ray_head:
    image: rayproject/ray:latest
    hostname: rayhead
    command: ray start --head --port=6379 --block
    ports:
      - 6379:6379
      - 8265:8265
      - 10001:10001
  ray_worker:
    image: rayproject/ray:latest
    depends_on:
      - ray_head
    entrypoint: ray start --address=rayhead:6379 --block
    deploy:
      mode: replicated
      replicas: 2