version: '3.3'

services:

  minio:
    image: minio/minio:latest
    hostname: minio
    environment:
      - GET_HOSTS_FROM=dns
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=fedn_admin
      - MINIO_ROOT_PASSWORD=f87yraDAS1
    command: server /data --console-address minio:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fedn_admin
      - MONGO_INITDB_ROOT_PASSWORD=f87yraDAS1
    ports:
      - 6534:6534
    command: mongod --port 6534

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - "mongo"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=6534
      - ME_CONFIG_MONGODB_ADMINUSERNAME=fedn_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=f87yraDAS1
      - ME_CONFIG_BASICAUTH_USERNAME=fedn_admin
      - ME_CONFIG_BASICAUTH_PASSWORD=f87yraDAS1
    ports:
      - 8081:8081

volumes:
  # CHANGE THIS IF YOU WANT TO PERSIST DATA ACROSS RUN's
  minio-data:
