network_id: fedn-test-network
token: fedn_token

control:
  state: idle
  helper: keras

statestore:
  type: MongoDB
  mongo_config:
    username: fedn_admin
    password: f87yraDAS1
    host: 130.238.28.254
    port: 6534

storage:
  storage_type: S3
  storage_config:
    storage_hostname: 130.238.28.254
    storage_port: 9000
    storage_access_key: fedn_admin
    storage_secret_key: f87yraDAS1
    storage_bucket: fedn-models
    context_bucket: fedn-context
    storage_secure_mode: False 
